const universities = [
  {
    id: 1,
    name: "National University of Sciences and Technology",
    abbreviation: "NUST",
    city: "Islamabad",
    sector: "Public",
    hec_ranking: 1,
    fee_per_semester: 150000,
    programs: ["Computer Science", "Engineering", "Business", "Mathematics", "Physics", "Social Sciences"],
    rating: 4.7,
    reviews_count: 1240,
    description: "NUST is Pakistan's premier research university, consistently ranked #1 by HEC. It offers world-class education in engineering, sciences, and business with strong industry linkages and a global outlook.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://nust.edu.pk",
    color: "#1a5276",
    established: 1991,
    campus_area: "242 acres",
    students: 8500,
    faculty: 650,
    acceptance_rate: 8,
    location: "H-12, Islamabad"
  },
  {
    id: 2,
    name: "Lahore University of Management Sciences",
    abbreviation: "LUMS",
    city: "Lahore",
    sector: "Private",
    hec_ranking: 2,
    fee_per_semester: 280000,
    programs: ["Business", "Computer Science", "Engineering", "Law", "Social Sciences", "Education"],
    rating: 4.8,
    reviews_count: 980,
    description: "LUMS is a nationally recognized research university known for its liberal arts approach, strong business school, and commitment to academic excellence with a need-based financial aid model.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: false,
      medical: true
    },
    website: "https://lums.edu.pk",
    color: "#27ae60",
    established: 1984,
    campus_area: "100 acres",
    students: 4000,
    faculty: 320,
    acceptance_rate: 6,
    location: "DHA, Lahore"
  },
  {
    id: 3,
    name: "COMSATS University Islamabad",
    abbreviation: "COMSATS",
    city: "Islamabad",
    sector: "Public",
    hec_ranking: 3,
    fee_per_semester: 95000,
    programs: ["Computer Science", "Engineering", "Management Sciences", "Mathematics", "Architecture", "Media Studies"],
    rating: 4.2,
    reviews_count: 870,
    description: "COMSATS is one of the largest multi-campus universities in Pakistan with focus on IT and engineering. It has multiple campuses across the country and a strong research output.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://comsats.edu.pk",
    color: "#8e44ad",
    established: 1998,
    campus_area: "300 acres",
    students: 30000,
    faculty: 1200,
    acceptance_rate: 18,
    location: "Park Road, Islamabad"
  },
  {
    id: 4,
    name: "National University of Computer and Emerging Sciences",
    abbreviation: "FAST",
    city: "Lahore",
    sector: "Private",
    hec_ranking: 4,
    fee_per_semester: 120000,
    programs: ["Computer Science", "Artificial Intelligence", "Data Science", "Software Engineering", "Cyber Security", "Business"],
    rating: 4.3,
    reviews_count: 720,
    description: "FAST-NUCES is Pakistan's top computer science university, renowned for its rigorous CS programs, hackathon culture, and producing highly skilled tech professionals for the industry.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: false,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: false
    },
    website: "https://nu.edu.pk",
    color: "#e74c3c",
    established: 1985,
    campus_area: "6 acres",
    students: 5500,
    faculty: 280,
    acceptance_rate: 12,
    location: "Ferozepur Road, Lahore"
  },
  {
    id: 5,
    name: "University of Engineering and Technology",
    abbreviation: "UET",
    city: "Lahore",
    sector: "Public",
    hec_ranking: 5,
    fee_per_semester: 65000,
    programs: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering", "Chemical Engineering", "Architecture"],
    rating: 4.1,
    reviews_count: 1100,
    description: "UET Lahore is the oldest and largest engineering university in Punjab, established during the British era. It has a legacy of producing top engineers and researchers in the country.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://uet.edu.pk",
    color: "#d35400",
    established: 1921,
    campus_area: "140 acres",
    students: 12000,
    faculty: 550,
    acceptance_rate: 15,
    location: "G.T. Road, Lahore"
  },
  {
    id: 6,
    name: "Institute of Business Administration",
    abbreviation: "IBA",
    city: "Karachi",
    sector: "Public",
    hec_ranking: 6,
    fee_per_semester: 110000,
    programs: ["Business Administration", "Computer Science", "Economics", "Mathematics", "Social Sciences", "Media Studies"],
    rating: 4.4,
    reviews_count: 650,
    description: "IBA Karachi is one of the oldest and most prestigious business schools in South Asia, established with the support of Wharton School. It offers exceptional programs in business and CS.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://iba.edu.pk",
    color: "#2c3e50",
    established: 1955,
    campus_area: "35 acres",
    students: 3200,
    faculty: 200,
    acceptance_rate: 10,
    location: "University Road, Karachi"
  },
  {
    id: 7,
    name: "Superior University",
    abbreviation: "Superior",
    city: "Faisalabad",
    sector: "Private",
    hec_ranking: 12,
    fee_per_semester: 75000,
    programs: ["Business", "Computer Science", "Engineering", "Pharmacy", "Allied Health Sciences", "Education"],
    rating: 3.9,
    reviews_count: 420,
    description: "Superior University Faisalabad is a growing private university offering quality education with modern facilities and an industry-oriented curriculum at an affordable fee structure.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: false,
      medical: true
    },
    website: "https://superior.edu.pk",
    color: "#16a085",
    established: 2001,
    campus_area: "15 acres",
    students: 4500,
    faculty: 180,
    acceptance_rate: 35,
    location: "Sargodha Road, Faisalabad"
  },
  {
    id: 8,
    name: "Government College University Lahore",
    abbreviation: "GCU",
    city: "Lahore",
    sector: "Public",
    hec_ranking: 7,
    fee_per_semester: 45000,
    programs: ["English", "Urdu", "Economics", "Physics", "Chemistry", "Mathematics", "Business"],
    rating: 4.0,
    reviews_count: 780,
    description: "GCU Lahore is a historic institution founded in 1864. It is known for its colonial architecture, rich academic tradition, and producing notable alumni including Nobel laureates.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://gcuf.edu.pk",
    color: "#7d3c98",
    established: 1864,
    campus_area: "40 acres",
    students: 10000,
    faculty: 400,
    acceptance_rate: 25,
    location: "The Mall, Lahore"
  },
  {
    id: 9,
    name: "University of the Punjab",
    abbreviation: "PU",
    city: "Lahore",
    sector: "Public",
    hec_ranking: 8,
    fee_per_semester: 35000,
    programs: ["Arts", "Science", "Commerce", "Law", "Medicine", "Engineering", "Education", "Islamic Studies"],
    rating: 3.8,
    reviews_count: 1500,
    description: "Punjab University is the largest and oldest university in Pakistan, established in 1882. It offers the widest range of programs and has a sprawling campus in the heart of Lahore.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://pu.edu.pk",
    color: "#c0392b",
    established: 1882,
    campus_area: "220 acres",
    students: 45000,
    faculty: 1800,
    acceptance_rate: 40,
    location: "Quaid-i-Azam Campus, Lahore"
  },
  {
    id: 10,
    name: "Air University",
    abbreviation: "AU",
    city: "Islamabad",
    sector: "Public",
    hec_ranking: 9,
    fee_per_semester: 85000,
    programs: ["Aerospace Engineering", "Computer Science", "Electrical Engineering", "Management Sciences", "Aviation"],
    rating: 4.1,
    reviews_count: 390,
    description: "Air University is a federally chartered public research university administered by the Pakistan Air Force. It specializes in aerospace engineering and computer science education.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://au.edu.pk",
    color: "#1abc9c",
    established: 2002,
    campus_area: "30 acres",
    students: 4000,
    faculty: 220,
    acceptance_rate: 20,
    location: "E-9, Islamabad"
  },
  {
    id: 11,
    name: "Quaid-i-Azam University",
    abbreviation: "QAU",
    city: "Islamabad",
    sector: "Public",
    hec_ranking: 10,
    fee_per_semester: 40000,
    programs: ["Physics", "Chemistry", "Mathematics", "Computer Science", "Management Sciences", "International Relations"],
    rating: 3.9,
    reviews_count: 610,
    description: "QAU Islamabad is a premier research university known for its strong science programs. It is located at the foot of the Margalla Hills and has a beautiful campus environment.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://qau.edu.pk",
    color: "#2980b9",
    established: 1967,
    campus_area: "700 acres",
    students: 13000,
    faculty: 500,
    acceptance_rate: 30,
    location: "Quaid-i-Azam University, Islamabad"
  },
  {
    id: 12,
    name: "NED University of Engineering and Technology",
    abbreviation: "NED",
    city: "Karachi",
    sector: "Public",
    hec_ranking: 11,
    fee_per_semester: 55000,
    programs: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science", "Architecture", "Textile Engineering"],
    rating: 4.0,
    reviews_count: 890,
    description: "NED University is one of the oldest engineering institutions in Pakistan, located in Karachi. It is known for producing skilled engineers for Pakistan's industrial sector.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://neduet.edu.pk",
    color: "#e67e22",
    established: 1921,
    campus_area: "90 acres",
    students: 10000,
    faculty: 420,
    acceptance_rate: 22,
    location: "University Road, Karachi"
  },
  {
    id: 13,
    name: "Bahauddin Zakariya University",
    abbreviation: "BZU",
    city: "Multan",
    sector: "Public",
    hec_ranking: 13,
    fee_per_semester: 30000,
    programs: ["Business", "Science", "Arts", "Engineering", "Medicine", "Agriculture", "Law"],
    rating: 3.7,
    reviews_count: 520,
    description: "BZU Multan is a major public university in South Punjab offering diverse programs. It serves as an important educational hub for southern Punjab and surrounding regions.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://bzu.edu.pk",
    color: "#9b59b6",
    established: 1975,
    campus_area: "500 acres",
    students: 18000,
    faculty: 600,
    acceptance_rate: 45,
    location: "Bosan Road, Multan"
  },
  {
    id: 14,
    name: "Mehran University of Engineering and Technology",
    abbreviation: "MUET",
    city: "Jamshoro",
    sector: "Public",
    hec_ranking: 14,
    fee_per_semester: 35000,
    programs: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Science", "Chemical Engineering", "Mining Engineering"],
    rating: 3.8,
    reviews_count: 350,
    description: "MUET Jamshoro is a leading engineering university in Sindh. It is known for its strong engineering programs and contribution to research in water resources and energy.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: true,
      medical: true
    },
    website: "https://muet.edu.pk",
    color: "#f1c40f",
    established: 1963,
    campus_area: "320 acres",
    students: 6000,
    faculty: 280,
    acceptance_rate: 35,
    location: "Jamshoro, Sindh"
  },
  {
    id: 15,
    name: "University of Sargodha",
    abbreviation: "UOS",
    city: "Sargodha",
    sector: "Public",
    hec_ranking: 15,
    fee_per_semester: 28000,
    programs: ["Business", "Science", "Arts", "Education", "Medicine", "Agriculture", "Law"],
    rating: 3.5,
    reviews_count: 280,
    description: "University of Sargodha is a public university serving the Sargodha division. It offers affordable quality education across multiple disciplines with a growing research profile.",
    facilities: {
      hostel: true,
      library: true,
      lab: true,
      sports: true,
      cafeteria: true,
      wifi: true,
      transport: false,
      medical: false
    },
    website: "https://su.edu.pk",
    color: "#3498db",
    established: 1975,
    campus_area: "150 acres",
    students: 8000,
    faculty: 300,
    acceptance_rate: 55,
    location: "University Road, Sargodha"
  }
];

const scholarships = [
  {
    id: 1,
    title: "HEC Need-Based Financial Aid",
    provider: "Higher Education Commission",
    amount: "Up to Rs. 100,000/semester",
    deadline: "2026-08-15",
    eligibility: "Matric/FSc with 60%+ marks, family income < 30,000/month",
    type: "Need-Based",
    description: "Complete tuition fee waiver plus monthly stipend for financially disadvantaged students across all HEC recognized universities.",
    status: "Open"
  },
  {
    id: 2,
    title: "Ehsaas Undergraduate Scholarship",
    provider: "Ehsaas Program",
    amount: "Up to Rs. 50,000/year",
    deadline: "2026-09-01",
    eligibility: "Matric/FSc with 50%+ marks, BISP registered families",
    type: "Need-Based",
    description: "Government scholarship for undergraduate students from low-income families, covering tuition and living expenses.",
    status: "Open"
  },
  {
    id: 3,
    title: "NUST Merit Scholarship",
    provider: "NUST",
    "amount": "100% Tuition Fee",
    deadline: "2026-07-30",
    eligibility: "NUST entry test score 80%+, FSc 85%+ marks",
    type: "Merit-Based",
    description: "Full tuition scholarship for top performers in NUST entrance exam. Renewable each semester based on GPA.",
    status: "Closing Soon"
  },
  {
    id: 4,
    title: "LUMS National Outreach Program",
    provider: "LUMS",
    amount: "Full Ride Scholarship",
    deadline: "2026-08-20",
    eligibility: "Matric/FSc with 80%+ marks, outstanding extracurriculars",
    type: "Merit-Based",
    description: "Comprehensive scholarship covering tuition, hostel, and living expenses for exceptional students from across Pakistan.",
    status: "Open"
  },
  {
    id: 5,
    title: "Punjab Educational Endowment Fund",
    provider: "PEEF",
    amount: "Up to Rs. 300,000/year",
    deadline: "2026-08-25",
    eligibility: "Punjab domicile, Matric/FSc with 60%+ marks",
    type: "Government",
    description: "Provincial scholarship for meritorious students of Punjab pursuing higher education in any recognized university.",
    status: "Open"
  },
  {
    id: 6,
    title: "COMSATS Merit Scholarship",
    provider: "COMSATS",
    amount: "25%-100% Tuition Fee",
    deadline: "2026-07-25",
    eligibility: "COMSATS admission test, FSc 75%+ marks",
    type: "Merit-Based",
    description: "Tiered merit scholarship based on admission test performance and academic record at COMSATS University.",
    status: "Closing Soon"
  },
  {
    id: 7,
    title: "FAST Scholarship for Women in Tech",
    provider: "FAST-NUCES",
    amount: "50% Tuition Fee",
    deadline: "2026-08-10",
    eligibility: "Female students, Computer Science program, 70%+ in FSc",
    type: "Special",
    description: "Encouraging women to pursue computer science with a half tuition scholarship and mentorship program.",
    status: "Open"
  },
  {
    id: 8,
    title: "Bait-ul-Mal Education Scholarship",
    provider: "Pakistan Bait-ul-Mal",
    amount: "Full Tuition + Stipend",
    deadline: "2026-09-15",
    eligibility: "Orphan students, Matric/FSc with 55%+ marks",
    type: "Need-Based",
    description: "Complete educational support for orphan students including tuition, hostel, books, and monthly living allowance.",
    status: "Open"
  }
];

const cities = ["Islamabad", "Lahore", "Karachi", "Faisalabad", "Multan", "Jamshoro", "Sargodha"];
const sectors = ["Public", "Private"];
const allPrograms = [...new Set(universities.flatMap(u => uprograms))];

const feeRanges = [
  { label: "Under Rs. 50,000", min: 0, max: 50000 },
  { label: "Rs. 50,000 - 100,000", min: 50000, max: 100000 },
  { label: "Rs. 100,000 - 200,000", min: 100000, max: 200000 },
  { label: "Above Rs. 200,000", min: 200000, max: Infinity }
];
